/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CopiesCopyIdRouteImport } from './routes/copies.$copyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CopiesCopyIdRoute = CopiesCopyIdRouteImport.update({
  id: '/copies/$copyId',
  path: '/copies/$copyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/signin': typeof SigninRoute
  '/wishlist': typeof WishlistRoute
  '/copies/$copyId': typeof CopiesCopyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/signin': typeof SigninRoute
  '/wishlist': typeof WishlistRoute
  '/copies/$copyId': typeof CopiesCopyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/signin': typeof SigninRoute
  '/wishlist': typeof WishlistRoute
  '/copies/$copyId': typeof CopiesCopyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/signin' | '/wishlist' | '/copies/$copyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/signin' | '/wishlist' | '/copies/$copyId'
  id: '__root__' | '/' | '/add' | '/signin' | '/wishlist' | '/copies/$copyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  SigninRoute: typeof SigninRoute
  WishlistRoute: typeof WishlistRoute
  CopiesCopyIdRoute: typeof CopiesCopyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copies/$copyId': {
      id: '/copies/$copyId'
      path: '/copies/$copyId'
      fullPath: '/copies/$copyId'
      preLoaderRoute: typeof CopiesCopyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  SigninRoute: SigninRoute,
  WishlistRoute: WishlistRoute,
  CopiesCopyIdRoute: CopiesCopyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
